'use client';
import { useState, type ReactNode } from 'react';
import { AnimatePresence, motion, MotionConfig } from 'framer-motion';
import { evaluateIllustration, money } from '@/lib/proof';
const Arrow = () => <span aria-hidden="true">↗</span>;
function Wordmark() { return <a className="wordmark" href="#top" aria-label="StockProof home"><span className="brand-symbol" aria-hidden="true">s<span>p</span></span>StockProof<span className="brand-dot">®</span></a>; }
function Eyebrow({ children }: { children: ReactNode }) { return <p className="eyebrow"><span className="tiny-square" />{children}</p>; }
function ButtonLink({ children }: { children: ReactNode }) { return <a className="button" href="#demo">{children}<Arrow /></a>; }
function TradeDemo() {
 const [amount, setAmount] = useState('500'); const [limit, setLimit] = useState('1'); const [step, setStep] = useState(0); const [error, setError] = useState(''); const [proof, setProof] = useState(() => evaluateIllustration(500, 1));
 function run(next = 1) { try { setProof(evaluateIllustration(Number(amount), Number(limit))); setError(''); setStep(next); } catch (e) { setError((e as Error).message); } }
 function reset() { setStep(0); setError(''); }
 return <section id="demo" className="demo-section section-shell"><div className="section-heading"><Eyebrow>THE TRADE, WITH THE FINE PRINT</Eyebrow><span className="mono demo-label"><span className="status-dot" /> INTERACTIVE CONCEPT · NOT LIVE DATA</span></div><div className="proof-workspace"><div className="intent-column"><span className="mono muted">01 / START WITH YOUR INTENTION</span><form onSubmit={e => { e.preventDefault(); run(); }}><div className="intent-sentence">Buy <label className="inline-field"><span aria-hidden="true">$</span><input aria-label="Investment amount in US dollars" type="number" min="10" max="100000" step="0.01" required style={{ width: `${Math.max(3, amount.length)}ch` }} value={amount} onChange={e => { setAmount(e.target.value); reset(); }} /></label> of <span className="asset-name">NVIDIA<span className="asset-dot" /></span> only if my total cost stays below <label className="inline-field limit-field"><input aria-label="Maximum additional cost percentage" type="number" min="0.1" max="10" step="0.01" required style={{ width: `${Math.max(1, limit.length)}ch` }} value={limit} onChange={e => { setLimit(e.target.value); reset(); }} /><span aria-hidden="true">%</span></label><span className="violet">.</span></div><p className="input-hint">Your amount. Your limit. Your decision.</p><button className="button" type="submit">{step ? 'Run again' : 'Prove this trade'}<Arrow /></button>{error && <p className="form-error" role="alert">{error}</p>}</form><div className="intent-footnote"><span className="asterisk">✳</span><p>Edit the underlined numbers.<br />No wallet. No transaction. Just clarity.</p></div></div><div className="reality-column"><div className="step-tabs" aria-label="Explore trade stages">{['Intent','Reality','Exit','Proof'].map((label,i) => <button key={label} onClick={() => i === 0 ? setStep(0) : run(i)} aria-pressed={step === i} className={step === i ? 'active' : ''}><span>0{i+1}</span>{label}</button>)}</div><div className="demo-output" aria-live="polite" aria-atomic="true"><AnimatePresence mode="wait"><motion.div key={step + '-' + proof.amount + '-' + proof.threshold} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: .18 }}>
 {step === 0 && <><span className="mono muted">THE NUMBER YOU SEE</span><div className="big-number">${amount || '0'}<span className="number-period">.</span></div><div className="annotation"><span>↳</span> There’s more to this number.</div><div className="preview-lines"><div><span>Actual entry cost</span><span>?</span></div><div><span>What comes back if you exit</span><span>?</span></div><div><span>The conditions in between</span><span>?</span></div></div><p className="small muted">Start with your intention. We’ll show you the other side.</p></>}
 {step === 1 && <><span className="mono muted">THE COST BEHIND THE BUY</span><div className="number-correction"><s>{money(proof.amount)}</s><span>↘</span></div><div className="result-number">{money(proof.total)}</div><div className="annotation"><span>↳</span> {money(proof.entryCost)} in illustrative entry costs.</div><div className="result-rule"><span>Additional entry cost</span><strong>{proof.costPercent.toFixed(2)}%</strong></div><p className={`outcome ${!proof.withinLimit ? 'blocked' : ''}`}>{proof.withinLimit ? '✓ Within your' : '× Exceeds or meets your'} {proof.threshold}% limit. {proof.withinLimit ? 'But keep reading.' : 'Entry condition not met.'}</p><button className="text-button" onClick={() => setStep(2)}>Now look at the exit <span>→</span></button></>}
 {step === 2 && <><span className="mono muted">IF YOU SOLD IN THIS EXAMPLE</span><div className="result-number">{money(proof.exitNow)}</div><div className="annotation"><span>↳</span> Exit Now. Not a future price.</div><div className="exit-mini"><div><strong>Exit Availability</strong><span>No live data connected</span></div><div><strong>Exit Risk</strong><span>Not assessed · source required</span></div></div><p className="small muted">An illustrative reverse quote. Availability and risk are separate questions, not predictions.</p><button className="text-button" onClick={() => setStep(3)}>See the complete proof <span>→</span></button></>}
 {step === 3 && <><div className="proof-title"><span className="mono">ILLUSTRATIVE PROOF / NVDA</span><span className="proof-seal">SP</span></div><h3 className="proof-result">{proof.withinLimit ? <>Entry fits.<br />The exit matters.</> : <>Your limit.<br />Not met.</>}</h3><div className="result-rule"><span>Entry total</span><strong>{money(proof.total)}</strong></div><div className="result-rule"><span>Exit Now · example</span><strong>{money(proof.exitNow)}</strong></div><div className="result-rule"><span>Live verification</span><strong>Not connected</strong></div><p className="small muted">Not an executable trade or investment advice. A real proof needs current quotes, contract checks, sources, and timestamps.</p><button className="text-button" onClick={reset}>Change your intention <span>↺</span></button></>}
 </motion.div></AnimatePresence></div><div className="demo-bottom mono"><span>EXAMPLE DATA / USD</span><span>YOU ALWAYS DECIDE ↗</span></div></div></div><p className="demo-disclaimer">A product walkthrough, not a market quote. Fixed illustrative rates explain the experience; no funds move and no asset is verified.</p></section>;
}
export default function Landing() {
 const [menu, setMenu] = useState(false);
 return <MotionConfig reducedMotion="user"><div id="top"><a href="#main" className="skip-link">Skip to content</a><header className="header section-shell"><Wordmark /><nav className={menu ? 'nav open' : 'nav'} aria-label="Main navigation"><a href="#product" onClick={() => setMenu(false)}>The product</a><a href="#how-it-works" onClick={() => setMenu(false)}>How it works</a><a href="#developers" onClick={() => setMenu(false)}>For developers <Arrow /></a></nav><a className="nav-cta" href="#demo">Try the demo <Arrow /></a><button className="menu-toggle" aria-label="Toggle navigation" aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? 'Close −' : 'Menu +'}</button></header><main id="main"><section className="hero section-shell"><div className="hero-topline"><Eyebrow>A CLEARER WAY INTO TOKENIZED STOCKS</Eyebrow><span className="mono edition">INDEPENDENT THINKING. INFORMED TRADING.</span></div><h1>You see the buy.<br /><span className="hero-last">We see the <em>trade.</em><svg aria-hidden="true" viewBox="0 0 370 28" preserveAspectRatio="none"><path d="M4 18C96 5 245 5 364 15M20 25C160 16 259 15 335 20" /></svg></span></h1><div className="hero-bottom"><p>The price is only the beginning.<br />See what you’re buying, what it really costs,<br className="desktop-break" /> and what it takes to get out. <strong>Before you commit.</strong></p><div className="hero-action"><ButtonLink>See the whole trade</ButtonLink><span className="mono muted">LESS BLIND TRUST. MORE PROOF.</span></div></div><div className="hero-margin-note"><span>↙</span>The part most<br />platforms leave out.</div></section><TradeDemo />
 <section id="product" className="manifesto section-shell"><motion.div initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }} transition={{ duration: .5 }}><Eyebrow>BUYING IS ONLY HALF THE TRADE</Eyebrow><div className="manifesto-grid"><h2>A buy button<br />isn’t the<br /><em>whole story.</em></h2><div className="manifesto-copy"><p className="large-copy">A ticker isn’t a contract.<br />A price isn’t a final cost.<br />And an entry isn’t an exit.</p><p>StockProof is being built to put the missing context in front of you. Not another signal telling you what to buy. A clearer view of the trade you’re already considering.</p><a className="text-button" href="#proofs">Read between the numbers <span>↓</span></a></div></div></motion.div></section>
 <section id="proofs" className="proofs-section section-shell"><div className="proof-editorial"><div className="proof-intro"><span className="mono">01 / ENTRY PROOF</span><h2>Know what<br />you’re getting <em>into.</em></h2><p>Four questions before a signature.<br />A reason to stop when something doesn’t add up.</p></div><div className="checks">{[['The asset','Is this the intended token and issuer?'],['The price','How does the quote compare to its reference?'],['The execution','What is the simulated total cost for your amount?'],['The conditions','What market and trading rules apply right now?']].map(([title,body],i)=><div className="check-row" key={title}><span className="mono">0{i+1}</span><div><h3>{title}</h3><p>{body}</p></div><span className="check-cross" aria-hidden="true">+</span></div>)}</div></div></section>
 <section className="exit-section"><div className="section-shell"><Eyebrow>02 / EXIT PROOF</Eyebrow><div className="exit-heading"><h2>Before you get in,<br />see the <em>way out.</em></h2><p>Three different questions.<br />Because “you can sell”<br />isn’t the same as “here’s how.”</p></div><div className="exit-cards">{[{n:'01',title:'Exit Now',tag:'SIMULATED',body:'What would come back if you sold this amount now?',foot:'A reverse quote for this moment. Not tomorrow’s price.',visual:'$486.20',label:'ILLUSTRATIVE RETURN ON $500'},{n:'02',title:'Exit Availability',tag:'PUBLISHED',body:'When, where, and under which rules can you exit?',foot:'Market hours and issuer rules. Not a guarantee of liquidity.',visual:'When & where.',label:'RULES, ROUTES & REDEMPTION'},{n:'03',title:'Exit Risk',tag:'OBSERVED',body:'What do current conditions tell you about the way out?',foot:'Observable signals with sources. Never a future price forecast.',visual:'Signals. Not bets.',label:'DEPTH, DISPERSION & CONTEXT'}].map(item=><div className="exit-card" key={item.n}><div className="exit-card-top"><span className="mono">{item.n}</span><span className="tag mono">{item.tag}</span></div><h3>{item.title}</h3><p>{item.body}</p><div className="exit-visual">{item.visual}<span className="mono">{item.label}</span></div><p className="exit-foot">{item.foot}</p></div>)}</div><p className="exit-principle"><span>↳</span> If we can’t verify it, we say so. Missing data should never look like certainty.</p></div></section>
 <section id="how-it-works" className="how-section section-shell"><Eyebrow>LESS FRICTION. MORE UNDERSTANDING.</Eyebrow><div className="section-title-row"><h2>From intention<br />to <em>informed decision.</em></h2><span className="oversized-arrow" aria-hidden="true">↘</span></div><div className="how-grid">{[['Say what you want.','A stock, an amount, and your conditions. Start with the decision, not a dashboard.'],['Look beneath the price.','The intended proof checks the asset, compares costs, and brings the exit into view.'],['See the whole trade.','Entry and exit, side by side. What checks out, what doesn’t, and what’s still unknown.'],['Make your call.','Go ahead, change the amount, or walk away. The final decision stays yours.']].map(([title,body],i)=><div key={title}><span className="mono step-number">0{i+1}</span><h3>{title}</h3><p>{body}</p></div>)}</div></section>
 <section id="developers" className="developer-section section-shell"><div><Eyebrow>BUILT FOR THE OTHER SIDE OF THE SCREEN</Eyebrow><h2>Clear for people.<br /><em>Structured for agents.</em></h2><p>A proposed proof layer for tokenized-stock experiences on BNB Smart Chain. Designed to connect asset data, quote simulation, and explicit user conditions.</p><a className="text-button" href="https://github.com/StkProof/vault-stockproof" target="_blank" rel="noreferrer">Explore the project on GitHub <Arrow /></a><div className="tech-chips mono"><span>BSC</span><span>RWA DATA</span><span>TRADE SIMULATION</span><span>AGENTIC WALLET</span></div></div><div className="code-sheet"><div className="code-header mono"><span>THE PROOF, NOT THE PROMISE</span><span>↗</span></div><pre><code><span className="code-muted">// Illustrative schema · not a live API</span>{'\n{\n  '}<span className="code-key">"intent"</span>{': "Buy $500 of NVIDIA",\n  '}<span className="code-key">"entry"</span>{': {\n    "total": 503.90,\n    "costPercent": 0.78\n  },\n  '}<span className="code-key">"exit"</span>{': {\n    "now": 486.20,\n    "availability": "unknown",\n    "risk": "not_assessed"\n  },\n  '}<span className="code-key">"mode"</span>{': "illustrative",\n  "executable": false\n}'}</code></pre><p className="small">Integration concept. This landing does not connect to financial APIs or sign transactions.</p></div></section>
 <section className="final-cta section-shell"><Eyebrow>THE WHOLE PICTURE. BEFORE THE CLICK.</Eyebrow><h2>Don’t just see the buy.<br /><em>See the whole trade.</em></h2><ButtonLink>Prove a trade</ButtonLink><span className="final-scribble" aria-hidden="true">↗</span></section></main><footer className="footer section-shell"><div className="footer-top"><Wordmark /><p>Clarity before commitment.</p><a href="https://github.com/StkProof/vault-stockproof" target="_blank" rel="noreferrer">GitHub <Arrow /></a><a href="#top">Back to top ↑</a></div><div className="footer-bottom"><p>© {new Date().getFullYear()} StockProof · An independent product concept.</p><p>Illustrative demo only. Not investment advice. No affiliation with NVIDIA.</p></div></footer></div></MotionConfig>;
}
